config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')), # Include urls from the menu app 
]

menu/urls.py
from django.urls import path
from . import views


app_name = 'menu'

urlpatterns = [
    path('', views.index, name='home'),
    path('<slug:name_menu>/', views.show_menu, name='page_menu'),
    path('<slug:name_menu>/<slug:name_category>/', views.show_category, name='page_category'),
    path('<slug:name_menu>/<slug:name_category>/<slug:name_subcategory>/', views.show_subcategory, name='page_subcategory'),
]

menu/models.py
from django.db import models
from django.urls import reverse

class Menu(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
    )
    url = models.CharField(
        max_length=255,
        blank=True,
    )
    named_url = models.CharField(
        max_length=255,
        blank=True,
    )
    
    menu_location_url = models.CharField(
        max_length=255,
        blank=True,
        default='/',
    )
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        if self.url:
            return self.url
        else:
            return reverse(self.named_url)
    
    def get_location_menu_url(self):
        return self.menu_location_url

    class Meta:
        verbose_name = 'Menu'
        verbose_name_plural = 'Menus'


class MenuItem(models.Model):
    menu = models.ForeignKey(
        Menu,
        on_delete=models.CASCADE,
    )
    title = models.CharField(
        max_length=255,
    )
    url = models.CharField(
        max_length=255,
        blank=True,
    )
    named_url = models.CharField(
        max_length=255,
        blank=True,
    )
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
    )
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        if self.url:
            return self.url
        else:
            return reverse(self.named_url)
    
    def get_item_index(self):
        items = list(MenuItem.objects.all())
        return items.index(self)
    
    class Meta:
        verbose_name = 'Menu Item'
        verbose_name_plural = 'Menu Items'
    

menu/views.py
from django.shortcuts import render
from . import models

def index(request):
    menus = models.Menu.objects.filter(menu_location_url=request.get_full_path())
    
    data = {
        'title': 'Home',
        'menus': menus,
    }
    
    return render(request, 'menu/index.html', context=data)

def show_menu(request, name_menu):
    menu = models.Menu.objects.get(named_url=name_menu)
    other_menus = models.Menu.objects.filter(menu_location_url=request.get_full_path())
    
    data = {
        'title': f'{name_menu}',
        'name_menu': menu,
        'other_menus': other_menus,
    }
    
    return render(request, 'menu/page_menu.html', context=data)

def show_category(request, name_menu, name_category):
    menu = models.Menu.objects.get(named_url=name_menu)
    category = models.MenuItem.objects.get(named_url=name_category)
    other_menus = models.Menu.objects.filter(menu_location_url=request.get_full_path())
    
    data = {
        'title': f'{name_category}',
        'name_menu': menu,
        'category': category,
        'other_menus': other_menus,
    }
    
    return render(request, 'menu/page_category.html', context=data)

def show_subcategory(request, name_menu, name_category, name_subcategory):
    subcategory = models.MenuItem.objects.get(named_url=name_subcategory)
    other_menus = models.Menu.objects.filter(menu_location_url=request.get_full_path())
    
    data = {
        'title': f'{subcategory}',
        'subcategory': subcategory,
        'other_menus': other_menus,
    }
    
    return render(request, 'menu/page_subcategory.html', context=data)

menu/templates/menu/index.html
{% load static %}
{% load menus_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/menu/index.css' %}">
</head>
<body>
  <a href="{% url 'menu:home' %}">Home</a>
  {% for menus_tags in menus %}
      {% draw_menu menus_tags as menu %}
      <ul class="menu">
          <a href="{{ menus_tags.get_absolute_url }}">
            <h2>{{ menus_tags }}</h2>
          </a>
          {% if menu|length > 0 %}
            {% for item in menu %}
              <li {% if request.resolver_match.url_name == item.named_url %} class="active"{% endif %}>
                <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
              </li>
            {% endfor %}
          {% else %}
            <li>No menu items found.</li>
          {% endif %}
        </ul>
  {% endfor %}
</body>
</html>

menu/templates/menu/page_category.html
{% load static %}
{% load menus_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <a href="{% url 'menu:home' %}">Home</a>
    {% draw_menu name_menu as menu %}
    <ul class="menu">
        <h2>{{ name_menu }}</h2>
        {% for item in menu %}
          {% if item.children.count > 0 %}
            <li {% if request.resolver_match.url_name == item.named_url %} class="active"{% endif %}>
              <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
              <ul>
                {% if item == category %}
                  {% for child in item.children.all %}
                    <li {% if request.resolver_match.url_name == child.named_url %} class="active"{% endif %}>
                      <a href="{{ child.get_absolute_url }}">{{ child.title }}</a>
                    </li>
                  {% endfor %}
                {% endif %}
              </ul>
            </li>
          {% else %}
            <li {% if request.resolver_match.url_name == item.named_url %} class="active"{% endif %}>
              <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
            </li>
          {% endif %}
          {% empty %}
            <li>No menu items found.</li>
        {% endfor %}
      </ul>

      {% for menus_tags in other_menus %}
      {% draw_menu menus_tags as menu %}
      <ul class="menu">
          <a href="{{ menus_tags.get_absolute_url }}">
            <h2>{{ menus_tags }}</h2>
          </a>
          {% if menu|length > 0 %}
            {% for item in menu %}
              <li {% if request.resolver_match.url_name == item.named_url %} class="active"{% endif %}>
                <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
              </li>
            {% endfor %}
          {% else %}
            <li>No menu items found.</li>
          {% endif %}
        </ul>
  {% endfor %}
</body>
</html>

menu/templates/menu/page_menu.html
{% load static %}
{% load menus_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
  <a href="{% url 'menu:home' %}">Home</a>
  {% draw_menu name_menu as menu %}
  <ul class="menu">
      <h2>{{ name_menu }}</h2>
      {% for item in menu %}
        {% if item.children.count > 0 %}
          <li {% if request.resolver_match.url_name == item.named_url %} class="active"{% endif %}>
            <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
            <ul>
              {% if item.get_item_index == 0 %}
                {% for child in item.children.all %}
                  <li {% if request.resolver_match.url_name == child.named_url %} class="active"{% endif %}>
                    <a href="{{ child.get_absolute_url }}">{{ child.title }}</a>
                  </li>
                {% endfor %}
              {% endif %}
            </ul>
          </li>
        {% else %}
          <li {% if request.resolver_match.url_name == item.named_url %} class="active"{% endif %}>
            <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
          </li>
        {% endif %}
        {% empty %}
          <li>No menu items found.</li>
      {% endfor %}
  </ul>

  {% for menus_tags in other_menus %}
      {% draw_menu menus_tags as menu %}
      <ul class="menu">
          <a href="{{ menus_tags.get_absolute_url }}">
            <h2>{{ menus_tags }}</h2>
          </a>
          {% if menu|length > 0 %}
            {% for item in menu %}
              <li {% if request.resolver_match.url_name == item.named_url %} class="active"{% endif %}>
                <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
              </li>
            {% endfor %}
          {% else %}
            <li>No menu items found.</li>
          {% endif %}
        </ul>
  {% endfor %}
</body>
</html>

menu/templates/menu/page_subcategory.html
{% load static %}
{% load menus_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <a href="{% url 'menu:home' %}">Home</a>
    <p>{{ subcategory }}</p>

    {% for menus_tags in other_menus %}
      {% draw_menu menus_tags as menu %}
      <ul class="menu">
          <a href="{{ menus_tags.get_absolute_url }}">
            <h2>{{ menus_tags }}</h2>
          </a>
          {% if menu|length > 0 %}
            {% for item in menu %}
              <li {% if request.resolver_match.url_name == item.named_url %} class="active"{% endif %}>
                <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
              </li>
            {% endfor %}
          {% else %}
            <li>No menu items found.</li>
          {% endif %}
        </ul>
  {% endfor %}
</body>
</html>